// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL0nigyqV5WeIaG7XJSs_zJBs8toxJqYY',
    appId: '1:1099100135991:web:bacbfd2b4647fbc47fd5b2',
    messagingSenderId: '1099100135991',
    projectId: 'expatswap-862e7',
    authDomain: 'expatswap-862e7.firebaseapp.com',
    storageBucket: 'expatswap-862e7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfHKBR8kqKZhvmmH9-LvlyuKgQDQHMPQA',
    appId: '1:1099100135991:android:d482bb02988826e67fd5b2',
    messagingSenderId: '1099100135991',
    projectId: 'expatswap-862e7',
    storageBucket: 'expatswap-862e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqMlWkFClG5uOw2mRz1TWIB9nussGb8YI',
    appId: '1:1099100135991:ios:ef17e67192182faa7fd5b2',
    messagingSenderId: '1099100135991',
    projectId: 'expatswap-862e7',
    storageBucket: 'expatswap-862e7.appspot.com',
    iosBundleId: 'com.example.expatswapFluttertask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqMlWkFClG5uOw2mRz1TWIB9nussGb8YI',
    appId: '1:1099100135991:ios:c10e5721e28456a57fd5b2',
    messagingSenderId: '1099100135991',
    projectId: 'expatswap-862e7',
    storageBucket: 'expatswap-862e7.appspot.com',
    iosBundleId: 'com.example.expatswapFluttertask.RunnerTests',
  );
}
